### ISSUE TITLE
Where is server.pub?

### ISSUE THREAD

**Issue by abear1538** [MariusQuabeck/telegram-cli-snap#3]
telegram-cli uses a file called server.pub which I need to specify the location of in the config file for nctelegram.

It is normally located in /etc/telegram-cli/

Where is the file located when installing using snap?

**Comment by MariusQuabeck** [comment]
it's somewhere in /snap/ but you can't edit or change the files inside the snap so I don't know if you can use the snap for nctelegram. maybe consider building telegram-cli from source

**Comment by abear1538** [comment]
Thank you for your response.

I was hoping that since you made the snap and because you're probably a lot more clever at the terminal than I am that you could help me locate the file.

**Comment by MariusQuabeck** [comment]
Well as I've said it's somewhere in /snap/telgram-cli/currrent but I don't think you will be able to access it because of confinement
